# Generated by Django 2.0.2 on 2018-02-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_auto_20180202_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('declared_currency', models.CharField(max_length=3)),
                ('declared_customs_value', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_additional_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductAdditionalInfo'),
        ),
    ]
