# Generated by Django 2.0.2 on 2018-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20180223_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_additional_info',
        ),
        migrations.AddField(
            model_name='product',
            name='actual_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='product',
            name='declared_currency',
            field=models.CharField(default='SGD', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='declared_customs_value',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='mobile', max_length=255),
        ),
    ]
