# Generated by Django 2.0.2 on 2018-02-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_auto_20180223_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='declared_currency',
            field=models.CharField(default='SGD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='declared_customs_value',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
